<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NJsonSchema" Version="11.5.2" />
    <PackageReference Include="System.Text.Json" Version="10.0.1" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\Jolt\Jolt.csproj" />
    <ProjectReference Include="..\Jolt.Testing\Jolt.Testing.csproj" />
  </ItemGroup>

</Project>
