<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="TestFiles\Documents\ConditionsDocument.json" />
    <EmbeddedResource Include="TestFiles\Documents\ExistenceDocument.json" />
    <EmbeddedResource Include="TestFiles\Documents\ExternalMethodsDocument.json" />
    <EmbeddedResource Include="TestFiles\Documents\LambdasDocument.json" />
    <EmbeddedResource Include="TestFiles\Documents\LoopDocument.json" />
    <EmbeddedResource Include="TestFiles\Documents\MathDocument.json" />
    <EmbeddedResource Include="TestFiles\Documents\MultiLevelDocument.json" />
    <EmbeddedResource Include="TestFiles\Documents\PipedMethodsDocument.json" />
    <EmbeddedResource Include="TestFiles\Documents\SingleLevelDocument.json" />
    <EmbeddedResource Include="TestFiles\Transformers\Conditions.json" />
    <EmbeddedResource Include="TestFiles\Transformers\Existence.json" />
    <EmbeddedResource Include="TestFiles\Transformers\ExternalMethodsWithAliases.json" />
    <EmbeddedResource Include="TestFiles\Transformers\ExternalMethods.json" />
    <EmbeddedResource Include="TestFiles\Transformers\Lambdas.json" />
    <EmbeddedResource Include="TestFiles\Transformers\Loops.json" />
    <EmbeddedResource Include="TestFiles\Transformers\Math.json" />
    <EmbeddedResource Include="TestFiles\Transformers\MultiLevelValueOf.json" />
    <EmbeddedResource Include="TestFiles\Transformers\PipedMethods.json" />
    <EmbeddedResource Include="TestFiles\Transformers\RangeVariables.json" />
    <EmbeddedResource Include="TestFiles\Transformers\SingleLevelValueOf.json" />
    <EmbeddedResource Include="TestFiles\Transformers\UsingBlock.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Text.Json" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Jolt\Jolt.csproj" />
  </ItemGroup>

</Project>
