<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <!-- Include all .csproj files except the one specified in Exclude -->
    <ProjectsToBuild Include="**/*.csproj" Exclude="Tests/Jolt.Json.DotNetFramework.Tests.csproj" />
  </ItemGroup>

  <Target Name="BuildAllExceptSpecific">
    <MSBuild Projects="@(ProjectsToBuild)" Targets="Build" />
  </Target>
</Project>