<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <Copyright>Chris Hannon</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="Xunit.DependencyInjection" Version="9.9.1" />
    <PackageReference Include="xunit.runner.reporters" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Jolt.Json.DotNet\Jolt.Json.DotNet.csproj" />
    <ProjectReference Include="..\..\Jolt.Json.Newtonsoft\Jolt.Json.Newtonsoft.csproj" />
    <ProjectReference Include="..\Jolt.Json.Tests.Cases\Jolt.Json.Tests.Cases.csproj" />
    <ProjectReference Include="..\Jolt.Json.Tests.Resources\Jolt.Json.Tests.Resources.csproj" />
    <ProjectReference Include="..\Jolt.Testing\Jolt.Testing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Unit\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="xunit.runner.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
