using System.Collections.Generic;

namespace Jolt.LanguageMetadata
{
    /// <summary>
    /// Represents the full set of language metadata that is consumed by IDE extensions.
    /// </summary>
    internal sealed class LanguageManifest
    {
        public string Comment { get; set; } = "Generated by IDE/Tools/Jolt.LanguageMetadata. Do not edit by hand.";

        public string JoltVersion { get; set; } = string.Empty;

        public List<LibraryMethodMetadata> Methods { get; set; } = new List<LibraryMethodMetadata>();
    }

    /// <summary>
    /// Represents a single standard library method as it is used from within a Jolt transformer.
    /// </summary>
    internal sealed class LibraryMethodMetadata
    {
        public string Name { get; set; } = string.Empty;

        public string? Description { get; set; }

        public string? Example { get; set; }

        public List<string> ValidOn { get; set; } = new List<string>();

        public bool IsValueGenerator { get; set; }

        public bool IsUnsafe { get; set; }

        /// <summary>
        /// Gets or sets the declared return type of the method as it would be written in C# (e.g. int, string,
        /// IJsonToken?, EvaluationResult?, or a user-defined type that Jolt serializes to JSON).
        /// </summary>
        public string ReturnType { get; set; } = string.Empty;

        public List<LibraryParameterMetadata> Parameters { get; set; } = new List<LibraryParameterMetadata>();
    }

    /// <summary>
    /// Represents a single parameter of a standard library method, excluding the evaluation context.
    /// </summary>
    internal sealed class LibraryParameterMetadata
    {
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the syntactic kind of the parameter, which determines how it is written in a transformer.
        /// One of: value, string, object, expression, lambda, range, rangeVariable, variablePath, enumeration, variableAlias.
        /// </summary>
        public string Kind { get; set; } = string.Empty;

        public bool IsOptional { get; set; }

        public bool IsVariadic { get; set; }

        public bool IsLazy { get; set; }
    }
}
